### ISSUE TITLE
use modules in nginx 1.20.1 coredump

### ISSUE THREAD

**Issue by aleccai8** [PolarisMesh/nginx-polaris#3]
use systemctl to start nginx file below
![image](https://user-images.githubusercontent.com/39586541/141673017-58541dfe-9a17-442f-9a95-acaa96328982.png)
and place polaris.yaml into /usr/local/sbin
![image](https://user-images.githubusercontent.com/39586541/141673048-ac4721a0-2fb2-4f1c-a371-86963596d5d8.png)
also make a polaris dictionary

the set the upstream as the README.md  and show debug log like below

![image](https://user-images.githubusercontent.com/39586541/141673097-bb73d34c-19f0-4594-bd15-e565ddd891db.png)

if you need any futher information, you can contact me into wechat group.

**Comment by aleccai0** [comment]
![image](https://user-images.githubusercontent.com/39586541/141673702-2b4385e2-a4b8-45cc-b966-2112f5e4aeab.png)

gdb backtrace full from one of core files

**Comment by wssgyyg** [comment]
#4
